### ISSUE TITLE
Make the BackboneExe Demo stuff contain all of the different interactive tests we've used.

### ISSUE THREAD

**Issue by gyurgyma** [lavinrp/GameBackbone#106]
Ryan and I have discussed extensively about how best to ensure that each and every one of our "Demos" and show off the "Demos" to the clients.

This Exe Demo Product thing will be the face of 0.1.0, Officially Alpha Release. The Demo should include but not be limited to the following:
1. Map Mode: This mode will contain the current NavigationDemoRegion that Brian's map generation code uses. This will also contain the GUI with multiple navigators to change which is being moved at the time. This will show the main features that can be used with GB
2. Swirly Mode: This mode will contain the spinning triangle test that SwirlySpriteBug is demonstrating now. This will allow us to test the few different options we have when rotating sprites. 
3. Clicky Mode: This mode will contain the RE example code that switches between two sprites by clicking. This should allow us to test any interRegion switching, child/parent or neighboring or whatever.
4. Etc Modes: Add other modes that seem needed for testing things that cannot be tested or instead show stuff that is hard to visualize.
5. A GUI for switching between modes. It will be imperative to show that our GUIs can stack atop each other.

**Comment by lavinrp** [comment]
@gyurgyma Before I take this farther I would like to talk about an issue I've run into.

I know we talked this one to death before, but now that I'm actually using it, I prefer children and neighbors of a region to be stored in a vector. Now that we are closer to actually implementing things that use children and neighbors, it seems like random access of a child / neighbor node will be far more common than adding/deleting from the list.

**Comment by lavinrp** [comment]
requires #121

**Comment by gyurgyma** [comment]
This is really really good. Exactly what my initial thought was.

I do however have a few extra features/comments:
1. I'd really like a reset button on DemoRegion so that each of the inherited guys will have it be default.
      - This will make it easier to reproduce bugs.
      - This will allow us to recall the constructors. I think that's important for manual testing.
      - This will make NavigationDemoRegion regenerate it's "terrain".
      - This will make SwirlyDemoRegion reset things like its origins and scales, how RRSprite will be used.
2. I would like SwirlyDemoRegion to have a set of buttons (like NDR) to select the different "init styles".
      - This will help us/others see how it can be used in a few different ways.
      - This would allow us to put an old school CompoundSprite into swirlyland and show that the same 
          can be done with sprite art offsets.
3. I think we should standardize DemoRegion naming conventions.
      - They could be really hyper descriptive, like RegionChange
      - They could be to distinguish only. So silly names could work. Hyper description should still be in 
           our documentation.
4. There should only be one RegionChangeDemoRegion stored on DemoSelectionRegion.
5. Maybe call DemoSelectionRegion "MainMenuRegion" or "DemoMainMenuRegion"
6. I want to talk to you about possible adding random elements to SwilyRemoRegion. I think it could be really cool to have different numbers of them a different distance. But maybe it's better to keep these demos simple.

**Comment by lavinrp** [comment]
1. I'd really like a reset button on DemoRegion so that each of the inherited guys will have it be default.
  * This will make it easier to reproduce bugs.
  * This will allow us to recall the constructors. I think that's important for manual testing.
  * This will make NavigationDemoRegion regenerate it's "terrain".
  * This will make SwirlyDemoRegion reset things like its origins and scales, how RRSprite will be used.
2. I would like SwirlyDemoRegion to have a set of buttons (like NDR) to select the different "init styles".
  * This will help us/others see how it can be used in a few different ways.
  * This would allow us to put an old school CompoundSprite into swirlyland and show that the same can be done with sprite art offsets.
3. I think we should standardize DemoRegion naming conventions.
  * They could be really hyper descriptive, like RegionChange
  * They could be to distinguish only. So silly names could work. Hyper description should still be in our documentation.
4. There should only be one RegionChangeDemoRegion stored on DemoSelectionRegion.
5. Maybe call DemoSelectionRegion "MainMenuRegion" or "DemoMainMenuRegion"
6. I want to talk to you about possible adding random elements to SwilyRemoRegion. I think it could be really cool to have different numbers of them a different distance. But maybe it's better to keep these demos simple.

**Comment by lavinrp** [comment]
Just discovered 1MB memory leak when resetting navigation demo region. Will need investigation.

When running navigation demo region repeatedly hit the reset button and watch memory usage fly

**Comment by lavinrp** [comment]
@bauerbp @gyurgyma 
From the heap analysis I've done I think the leak may come from regenerating the clusters. Not 100% sure though. 

The primary source of the leak is GB::Point2D<int> though. Some of these Point2Ds dont report where they come from, but some of them report to come from cluster.

There is other minor leaking going on for other things too. Some of it seems to be from the mersenne twister.

There also seems to be a significant chunk of allocations coming from sf::Sprite.

To reproduce results run backboneEXE, go to navigation demo region, turn on heap profiling, hit reset. Take a snapshot then hit reset and take a second snapshot.

After both snapshots have been recorded simply click on the blue number indicating the number of allocations.

This may be a false positive, but its the only lead I have right now.

**Comment by gyurgyma** [comment]
Leak's gone.
