### ISSUE TITLE
Static Polymorphism for CoreEventController

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#127]
Static Polymorphism for CoreEventController should allow for it to be much more efficient (inlining of functions and no vtable lookups).

Making it a [concept](https://www.boost.org/doc/libs/1_60_0/libs/concept_check/concept_check.htm) or a [CRTP ](https://www.fluentcpp.com/2017/05/12/curiously-recurring-template-pattern/) class.

We could also just make it a template without any concept.

Pros of concept

- More effectively demonstrates intent
- Zero run time overhead
- Will be added to next c++ standard
- Users just have to implement a class that conforms to the concept

Cons of concept

- Requires Boost

Pros of CRTP
 - Doesn't Require another library added to GB
 - demonstrates intent of class
 - Zero run time overhead

Cons of CRTP
 - poor compiler warnings (I think)
 - Requires some weird template magic

Pros of template
 - Doesn't Require another library added to GB
 - Can be turned into a concept after concepts are added to the language
 - Zero run time overhead

Cons of template
 - poor compiler warnings
 - intent of class unclear

**Comment by gyurgyma** [comment]
Using CRTP seems to have two major issues: 
Firstly, the interface is not nice. In my original attempt, we were forcing the users to implement every single function, even ones that they are not using. 

Second, after a huge redesign, all seemed like it would work but it ended up if we needed to access variables from the CEC within our manager classes we needed to pass the CEC. This is a vtable lookup. We discussed possible having another CRTP for this class, but we quickly found in order to have this work, it would be infinitely recursive... CRCRCRCRCR...TP

**Comment by lavinrp** [comment]
I created a CRTP implementation.
i127-CEC_CRTP

I think I have things working so that we get client defined behavior without any vtable calls.

Tested in demo regions and UnitTests.
Behavior seems unchanged.

Users need only add the template to the end of their inheritance.

before:
> class MyCEC : public GB::CoreEventController {/*stuff*/}


After:
> class MyCEC : public GB::CoreEventController\<MyCEC\> {/*stuff*/}


@gyurgyma would you mind taking a look?

**Comment by gyurgyma** [comment]
Merged into Dev
