### ISSUE TITLE
CompoundSprite should be recursive and generalized

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#182]
Compound sprites should be able to hold other compound sprites. This would provide a nice way to do things to some arbitrary subset of the compound sprite.

**Comment by lavinrp** [comment]
Make sure to test RelativeRotation sprite recursive.

**Comment by gyurgyma** [comment]
CompoundSprite should not only be recursive, but generalized to hold any amount of sf::Drawables. This would allow CompoundSprite to act more akin to a group of drawables, and using mixed sf::Drawable types to create a single "Sprite"

**Comment by gyurgyma** [comment]
The requirements for generalization are as follows:
- The user should be able to store CompoundSprites in a single vector. This means that even if CompoundSprites are storing different types, they should be able to be stored in one vector, ei: std::vector<CompoundSprite>. This sort of rules out templating, unless we default the template to something.
- The CompoundSprite should store all of its components in a single vector. This requirement is in order to optimize drawing (especially with priority). If they are stored in different vectors, then priority drawing is no longer simply looping over each in order, they would need to be sorted or zippered or something like that. A single vector would allow the components to be looped over a single time during the draw call, thus optimizing it.
- Indirections (visits, virtuals, etc) should be avoided on the draw call if possible. This may be an early optimization, and is not inherently a requirement. But if we can design the same API with few indirections on the draw (perhaps more on the add) then we should.

**Comment by lavinrp** [comment]
CompoundSprite is a data sink. To express that we are taking ownership of data we do not want to take data with a begin and end iterator.

Constructor should take a variable number of vectors. Each vector should be a vector containing types that satisfy the component concept.

Add should be the same way.

**Comment by lavinrp** [comment]
Look at https://youtu.be/6HoxXeEBtW0
and ensure that our fold expression is not broken by `operator,`

`(addComponentFunction(std::forward<Components>(componentsToAdd)), ...);`

**Comment by lavinrp** [comment]
@gyurgyma 
Fix test names to not include toDrawableVector
Figure out why tests are failing on your laptop and my desktop.
