### ISSUE TITLE
Demo Crashes at Runtime in VS2019

### ISSUE THREAD

**Issue by lavinrp** [lavinrp/GameBackbone#199]
Looks like this is probably from clusters. If it is in clusters in addition to making the crash go away there should be a unit test to cover whatever is going wrong.

**Comment by lavinrp** [comment]
The bug is in ClusterGreenhouse::growCluster

**Comment by lavinrp** [comment]
We ALWAYS dereference the end iterator of borderPointSet on our first pass through. (because begin == end in an empty set)
I have no idea how this ever worked before.
I have no idea how valgrind didn't detect this before.
We were probably reading into random memory that just happened not to explode.

This isn't really unit testable. It never should have worked. Perhaps there is a valgrind setting that I missed when manually running it over the demo.

When we set up our CI we should ensure that valgrind always runs on the strictest settings.

**Comment by lavinrp** [comment]
Clusters really doesn't fit the quality we expect in GB 0.2.1 forward and this change wont fix that. 
This will fix an off by one bug that for some reason was always causing a crash in vs 2019, but never causing a crash in any other environment.

I don't really understand how this wasn't periodically exploding across all of our other platforms.
We had a random chance of going one past the end every time we try to add a point to a cluster.

Perhaps the other standard libraries were just indexing into random memory and (un)fortunately not exploding?

That doesn't explain why valgrind never found the issue.
Perhaps I wasn't running valgrind on its most strict settings.

When we set up our CI we'll need to be sure that valgrind is checking for just about everything.

**Comment by lavinrp** [comment]
Fix is on branch: i199 - DemoCrashes

**Comment by gyurgyma** [comment]
@lavinrp I'm trynna figure out if this is the right fix. An off by one error doesn't seem like the issue here. uniDist should be exclusive on the right hand side (ei: [0,1)). But, that said, when using std::advance, what is the number we can advance by?

I quickly reworked the code to be what it was before to check the output numbers. Here is a real example: Size: 96, Number: 95.506303538262500

So, if we set the iterator to begin(), and then advance the iterator by (assuming integerized) 95.5, do we get end, or the last iterator? If it is end(), then I think this is a proper off by one issue and you've fixed it. If we get the last point, then subtracting one from 95.5 will actually ignore our last borderPoint. 

I guess understanding both std::advance and uniDist and their interaction is helpful here, but it's such a niche case. Also, it may be ok that this is the fix if we rewrite clusters in the future.

Overall, I think answering the above questions will get us our answer. But, for me, this will always be unsatisfactory as I can't find anything on the web about vs2019 changing any of this functionality from vs2017.

**Comment by lavinrp** [comment]
Switched from magic -1 to int cast of rand

**Comment by gyurgyma** [comment]
Ryan merged this in.
