### ISSUE TITLE
Utility function to make std::vector<Drawable*> from std::vector<"DrawableChild"*>

### ISSUE THREAD

**Issue by gyurgyma** [lavinrp/GameBackbone#201]
addDrawable is optimized for bulk and pessimized for single. The problem here though, is that not many people are storing their Drawables as std::vector\<sf::Drawable*\>. that means that in order to use the bulk function, users have to manually construct a std::vector<sf::Drawable*> to pass to us. This is silly and smell of a bad API.

Let's create a template utility function that turns std::vector<Sprite*>/std::vector<CompoundSprite*/etc. into std::vector<sf::Drawable*> for them.

**Comment by sheeralm** [comment]
@lavinrp We implemented this, but are faced with an issue between the two functions, which are covering both Sprite vector and Sprite* vector arguments. The second function told me that it was already declared, because it was. Is there a way to specify whether the argument is a pointer or not?

**Comment by lavinrp** [comment]
@sheeralm 
Yes.

This is the really hard part that I mentioned. I dont really want to make you do the hard 
There are two ways to solve the problem:
Easy way: give them different names

Hard way: SFINAE (concepts in c++ 20)

I think the hard way is the way to go for an easy to use API.
Since you're only just learning templates I dont want to make you go through the pain of learning SFINAE yet.

**Comment by lavinrp** [comment]
Note:
C++ 20 changes a lot
Instead of SFINAE we get concepts to help make this easy

I thought that std::span would change a lot too, but after doing a bunch of research it doesn't seem to make things much better. https://godbolt.org/z/SDcvyZ


@gyurgyma We should look at things later and figure out if we want this to be a vector of pointers or a vector of references.
In my experimentation I've found that span may have some issues when used with references (at least GSL span).

As we switch some things to std::reference_wrapper we may need some more utilities like reference_static_cast, reference_dynamic_cast, etc...

**Comment by gyurgyma** [comment]
I agree that SFINAE and eventually concepts are the way to handle this. Looking at this godbolt confuses me (its the extra asterisk in the cast). Personally, I'm not fully in on span yet. Vector just seems so much cleaner to my head. I think the swap to std::reference_wrapper should be a discussion in its own right and we shouldn't cloud too much of this issue with it now.

**Comment by lavinrp** [comment]
@gyurgyma agreed on the reference wrapper.
Its just something that I ran into when playing around with things here and I figured that I should mention it somewhere.

**Comment by gyurgyma** [comment]
Should GameRegion store const Drawable*s? Can it? I have no idea.

**Comment by gyurgyma** [comment]
This ended up being a fair amount of work. We discovered a better way to do this. 

What we want to try is rather than converting a whole vector of DrawableChild*s instead to just "cast" the iterator of the vector and iterate over it, but return the Drawable* on the dereference of the iterator. This has led us to see boost::transform_iterator and boost:iterator_adapter, which is close to want. It seems that its usage is a bit complicated and slightly too generic.

We are trying to make an std compliant version of this that matches both the legacy and C++20 concepts. Reassigning to Ryan.

**Comment by gyurgyma** [comment]
@lavinrp Preliminary review before it's needed:
- Alphabetize SFUtil.h SF includes
- NavigationDemoRegion.cpp
  - Line29: Remove numbers at the end of comment
  - Line 356: Capitalize comment and put onto a single line
- SFUtilTests.cpp: can you comment which tests are strictly compile tests
- Remove const cast in SFUtil.h

**Comment by lavinrp** [comment]
GameRegion is being refactored to have a better ownership model.
This will not be an issue under the new design.
