### ISSUE TITLE
Remedy CoreEventController Unit Test Inconsistency

### ISSUE THREAD

**Issue by malexmc** [lavinrp/GameBackbone#89]
CoreEventController has issues when it runs on a window that has not fully initialized. This needs to be investigated and remedied.

**Comment by lavinrp** [comment]
@malexmc is this done? Should this issue be closed?
feel free to close if so.

**Comment by malexmc** [comment]
i89-DeflakeCoreEventControllerTest:
     -Added public method CoreEventController::windowIsOpen() which calls sf::Window::isOpen() on the protected internal window to see if the window has completed opening.
     -Added a check in CoreEventController_RunLoop_No_Window_Event so it won't run until the GameRegion's window is open.

Moving issue to review to confirm the creation of windowIsOpen() is both welcome and as desired.

**Comment by gyurgyma** [comment]
all method names that return bool should start with is/has/etc. Rename windowIsOpen() to isWindowOpen(). will do an actual code review tomorrow/when thats updated. look at StyleGuide.txt in the GameBackbone git folder for more info on our naming conventions.

**Comment by malexmc** [comment]
windowIsOpen() renamed to isWindowOpen()

**Comment by lavinrp** [comment]
I like the simplicity of the solution and it does do its job, but after looking at the this function's use in the tests I'm afraid it may just be brushing the problem under the rug.

We haven't had any issues caused by this in production code, but we may down the line. With the unit test being safe from this error it will be hard to spot the error does ever show up in production.

Because of this, I think we should:

1. Remove the isWindowOpen function.
2. Place the logic to spin until the window is open at the start of CoreEventController::runLoop
3. Remove the added check from the unit tests.

This way all GB logic, and the logic of all GB clients will wait for the window to be ready.

thoughts?

**Comment by malexmc** [comment]
i89-DeflakeCoreEventControllerTest: 
    -Added logic to GB::CoreEventController::runLoop() to check if window is open before proceeding.

**Comment by gyurgyma** [comment]
Wait, so there's no better way to do this than to have a while loop checking the window is open just before we check the window is open? That seems really silly. Is that just to make sure we sit at that part of the code until we're good to go? 

Also, the comment has 2 "before"s.

**Comment by gyurgyma** [comment]
I've also run extensive tests, I still hit this error about 1 out of every 4 times. This needs significant looking into I think. I think we need to sit down and discuss what's happening and where and really put our brain muscles to the test.

**Comment by malexmc** [comment]
i89-DeflakeCoreEventController:
    -Changed the mock postHandleEvent() function to reset the "hasFinished...Event" flags as it finishes.

    It seems like the flakiness of the tests occurred when several events were handled during the execution of the tests. Previously, when one event was handled, all related flags were set. As the second event was beginning to be handled, it would expect those flags not to be set, thus failing. Having postHandleEvent() reset the flags will preserve the intended functionality.
